apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: httpd-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-frontend
  strategy:
    type: RollingUpdate
    rollingParams:
      updatePeriodSeconds: 1 
      intervalSeconds: 1 
      timeoutSeconds: 120 
      maxSurge: "20%" 
      maxUnavailable: "10%" 
      pre: {} 
      post: {}
  template:
    metadata:
      labels:
        app: httpd-frontend
    spec:
      containers:
      - image: example-registry-quay-quay-enterprise.apps.ocp-spoke1.lab.local/quayadmin/testrepo/rhel8/httpd-24:latest
        imagePullPolicy: Always
        name: httpd-rhel7
          #Limits:
          #cpu:     2
          #memory:  4Gi
          #Requests:
          #cpu:      2
          #memory:   2Gi
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 8443
          name: https-port
---
apiVersion: v1
kind: Service
metadata:
  name: http-port
  labels:
    app: httpd-frontend
spec:
  ports:
    - port: 8080
      name: http-port
      protocol: TCP
      targetPort: 8080
  selector:
    app: httpd-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: https-port
  labels:
    app: httpd-frontend
spec:
  ports:
    - port: 8443
      name: https-port
      protocol: TCP
      targetPort: 8443
  selector:
    app: httpd-frontend
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: httpd-frontend
  managedFields:
  name: http-port
spec:
  port:
    targetPort: http-port
  to:
    kind: Service
    name: http-port
    weight: 100
